dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
  - test/gemfiles/activerecord52.gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
services:
  - postgresql
  - mysql
script: bundle exec rake test
before_install:
  - mysql -e 'CREATE DATABASE groupdate_test;'
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - psql -c 'CREATE DATABASE groupdate_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
